language: python
python:
  - "2"
  - "2.6"
  - "2.7"
  - "3"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install .
   - pip install -r requirements-test.txt
# command to run tests
script: 'mamba'
